# Site settings
title: "Paulo V."
description: "Personal website and blog about machine learning, AI, and research"
author: "Paulo V."
email: "paulvca@pm.me"
baseurl: ""
url: "https://pvictorca.github.io"

# Build settings
highlighter: rouge
permalink: /publications/:year/:month/:day/:title/
environment: prod
markdown: kramdown

# Plugins
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-katex

# Plugin settings
katex:
  js_path: "assets"
  rendering_options:
    throw_error: false
    error_color: "#cc0000"

# Jekyll Scholar settings
scholar:
  style: apa
  locale: en
  
# Feed settings
feed:
  posts_limit: 10

# SEO and social
twitter_username: paulvca
github_username: pvictorca

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - README.md